### ISSUE TITLE
Move `Oddities.Resources.Dib` to `Oddities.Dib`

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Oddities#13]
Leaving the old location and marking it as obsolete, if possible.

**Comment by shivangnayar-crypto** [comment]
cant find Oddities.Resources.Dib  folder

**Comment by ForNeVeR** [comment]
Because it is not a folder, but a type: https://github.com/ForNeVeR/Oddities/blob/ce8808748900464f4c75796e5d74c47fa61040c9/Oddities.DIB/Dib.fs#L1-L9

I meant that I'd like to move it from the `Resources` namespace to just `Oddities`.

`Resources` was a leftover from the previous project this type was living it; now, it has no relation to any "resources".

**Comment by shivangnayar-crypto** [comment]
ok
i have created a pull request https://github.com/ForNeVeR/Oddities/pull/14
please review it

**Comment by shivangnayar-crypto** [comment]
Is it fine now?

**Comment by shivangnayar-dev** [comment]
can you check and guide me if it is correct?
